<a href="https://colab.research.google.com/github/Sara0894/2025-1-CD/blob/main/Parcial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [ ]:
import numpy as np

**1. Crea un array de NumPy con los números del 1 al 100 e imprime los múltiplos de 7.**

In [ ]:
numbers_array = np.arange(1, 101)
print("Múltiplos de 7:", numbers_array[numbers_array % 7 == 0])

Múltiplos de 7: [ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]


**2. Crea una matriz de 4x4 con números aleatorios enteros entre 10 y 50. Luego reemplaza los valores impares por -1.**

In [ ]:
np.random.seed(42)
random_matrix = np.random.randint(10, 51, size=(4, 4))
original_matrix = random_matrix.copy()
random_matrix[random_matrix % 2 != 0] = -1
print("Matriz original:\n", original_matrix)
print("Matriz con impares reemplazado:\n", random_matrix)

Matriz original:
 [[48 38 24 17]
 [30 48 28 32]
 [20 20 33 45]
 [49 33 12 31]]
Matriz con impares reemplazado:
 [[48 38 24 -1]
 [30 48 28 32]
 [20 20 -1 -1]
 [-1 -1 12 -1]]


**3. Genera una matriz de 5x5 con valores entre 0 y 1 distribuidos uniformemente. Luego, calcula la suma por columnas.**

In [ ]:
np.random.seed(123)
uniform_matrix = np.random.rand(5, 5)
column_sums = uniform_matrix.sum(axis=0)
print("Matriz aleatoria: \n", uniform_matrix)
print("Suma por columnas: \n", column_sums)

Matriz aleatoria: 
 [[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]]
Suma por columnas: 
 [2.83515003 3.02787677 2.25016052 2.23449945 2.76390171]


**4. Dado un array arr = np.array([1, 2, 3, 4, 5]), obtén su versión invertida.**

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
reversed_array = original_array[::-1]
print("Array original: \n", original_array)
print("Array invertido: \n", reversed_array)

Array original: 
 [1 2 3 4 5]
Array invertido: 
 [5 4 3 2 1]


**5. Crea una matriz identidad de 6x6 y multiplícala por 3. ¿Qué observas?**

In [ ]:
indentity_matrix = np.eye(6)
print("Matriz identidad: \n", indentity_matrix)
print("Matriz identidad multiplicada por 3: \n", indentity_matrix * 3)

Matriz identidad: 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Matriz identidad multiplicada por 3: 
 [[3. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]


Se obtiene una matriz diagonal donde los números 1 en diagonal son reemplazados con números 3. Además se observan números ceros en el resto de la matriz.

**6. Crea un array de 15 elementos entre 1 y 100 y ordénalo de mayor a menor.**

In [ ]:
np.random.seed(10)
random_array = np.random.randint(1, 101, size=15)
random_array.sort()
desc_array = random_array[::-1]
print("Array original: \n", random_array)
print("Array ordenado de mayor a menor: \n", desc_array)

Array original: 
 [ 1  9 10 12 16 17 29 30 37 41 55 65 74 90 94]
Array ordenado de mayor a menor: 
 [94 90 74 65 55 41 37 30 29 17 16 12 10  9  1]


**7. Usa NumPy para calcular la media, la mediana y la desviación estándar de un
array de 30 valores aleatorios entre 0 y 100.**

In [ ]:
np.random.seed(99)
arr_30 = np.random.randint(0, 101, size=30)
print("Array de 30 valores: \n", arr_30)
print("Media: \n", np.mean(arr_30))
print("Mediana: \n", np.median(arr_30))
print("Desviación estándar: \n", np.std(arr_30))

Array de 30 valores: 
 [ 1 35 57 40 73 82 68 69 52  1 23 35 55 65 48 93 59 87  2 64 12 40 72 20
 59 39 79 47 27 62]
Media: 
 48.86666666666667
Mediana: 
 53.5
Desviación estándar: 
 25.192238663701346


**8. Crea un array bidimensional 6x3 con valores aleatorios y reemplaza la fila con el menor promedio por ceros.**

In [ ]:
np.random.seed(7)
matrix_6x3 = np.random.rand(6,3)
row_means = matrix_6x3.mean(axis=1)
min_row_idx = np.argmin(row_means)
modified_matrix = matrix_6x3.copy()
modified_matrix[min_row_idx] = 0
print("Matriz original: \n", matrix_6x3)
print("Promedios por fila", row_means)
print("Fila con menor promedio (índice): ", min_row_idx)
print("Matriz modificada: \n", modified_matrix)

Matriz original: 
 [[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]
 [0.50112046 0.07205113 0.26843898]
 [0.4998825  0.67923    0.80373904]
 [0.38094113 0.06593635 0.2881456 ]
 [0.90959353 0.21338535 0.45212396]]
Promedios por fila [0.43154544 0.74665019 0.28053686 0.66095051 0.24500769 0.52503428]
Fila con menor promedio (índice):  4
Matriz modificada: 
 [[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]
 [0.50112046 0.07205113 0.26843898]
 [0.4998825  0.67923    0.80373904]
 [0.         0.         0.        ]
 [0.90959353 0.21338535 0.45212396]]


**9. Crea un array 3x4 y aplica la función np.cumsum() por filas.**

In [ ]:
np.random.seed(15)
matrix_3x4 = np.random.randint(0, 10, size=(3, 4))
cumulatives_sum = np.cumsum(matrix_3x4, axis=1)
print("Matriz original: \n", matrix_3x4)
print("Suma acumulada por filas: \n", cumulatives_sum)

Matriz original: 
 [[8 5 5 7]
 [0 7 5 6]
 [1 7 0 4]]
Suma acumulada por filas: 
 [[ 8 13 18 25]
 [ 0  7 12 18]
 [ 1  8  8 12]]


**10. Dado el siguiente array:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), extrae solo los elementos de la diagonal principal.**

In [ ]:
squeare_matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
main_diagonal = np.diagonal(squeare_matrix)
print("Matriz original: \n", squeare_matrix)
print("Diagonal principal: \n", main_diagonal)

Matriz original: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Diagonal principal: 
 [10 50 90]


# **Pandas**

In [ ]:
import pandas as pd

**11. Crea un DataFrame con las columnas: Nombre, Edad, Ciudad, Salario con al menos 5 registros. Filtra los registros con salario mayor a 2.000.000.**

In [ ]:
data = {
        'Name': ['Veronica', 'Amelia', 'Sara', 'Samuel', 'Andres','Valentina','Jorge'],
        'Age': [28, 22, 25, 29, 31, 42, 33],
        'City': ['Cali', 'Bucaramanga', 'Cartajena', 'Medellin', 'Popayan', 'Cucuta', 'Pereira'],
        'Salary': [3700000, 1500000, 400000, 3200000, 2100000, 360000, 2900000]
    }
df = pd.DataFrame(data)
filtered_df = df[df['Salary'] > 2000000]
print("Salarios > 2.000.000")
print(filtered_df)

Salarios > 2.000.000
       Name  Age      City   Salary
0  Veronica   28      Cali  3700000
3    Samuel   29  Medellin  3200000
4    Andres   31   Popayan  2100000
6     Jorge   33   Pereira  2900000


**12. Importa un CSV desde una URL o archivo local y muestra las 10 primeras filas y las 5 últimas.**

In [ ]:
import pandas as pd
url_csv = "https://www.datos.gov.co/resource/3t73-n4q9.csv"
df_online = pd.read_csv(url_csv)
pd.set_option('display.max_columns', 4 )
print("Primeras 10 filas:")
print(df_online.head(10))
print("Ultimas 5 filas")
print(df_online.tail(5))

Primeras 10 filas:
               principio_activo unidad_de_dispensacion  ... factoresprecio  \
0                     Midazolam                Ampolla  ...           Alto   
1               Acido Valproico                Tableta  ...          Medio   
2               Acido Valproico                Tableta  ...          Medio   
3                    Fluoxetina                Capsula  ...          Medio   
4                Proximetacaina                 Frasco  ...          Medio   
5                Proximetacaina                 Frasco  ...          Medio   
6  Immunoglobulina Antitimocito                   Vial  ...          Medio   
7                    Alopurinol                Tableta  ...           Bajo   
8                   Haloperidol                Tableta  ...           Alto   
9                   Haloperidol                Tableta  ...           Bajo   

  numerofactor  
0            3  
1            2  
2            2  
3            2  
4            2  
5            2  
6  

**13. A partir de un DataFrame con una columna de fechas, crea una nueva columna
con el nombre del mes.**

In [ ]:
data = {
        'Name': ['Veronica', 'Amelia', 'Sara', 'Samuel', 'Andres','Valentina','Jorge'],
        'Age': [28, 22, 25, 29, 31, 42, 33],
        'Birthday': ['20-01-1997', '12-08-2003', '18-06-2000', '20-10-1996', '28-07-1994', '07-05-1983', '15-03-1992']
    }
df = pd.DataFrame(data)
df['Birthday'] = pd.to_datetime(df['Birthday'], format='%d-%m-%Y')
df['Month'] = df['Birthday'].dt.strftime('%B')
print("Mes de cumpleaños:")
print(df)

Mes de cumpleaños:
        Name  Age   Birthday    Month
0   Veronica   28 1997-01-20  January
1     Amelia   22 2003-08-12   August
2       Sara   25 2000-06-18     June
3     Samuel   29 1996-10-20  October
4     Andres   31 1994-07-28     July
5  Valentina   42 1983-05-07      May
6      Jorge   33 1992-03-15    March


**14. Agrupa un DataFrame por la columna Ciudad y calcula el salario promedio por
ciudad.**

In [ ]:
data = {
        'Name': ['Veronica', 'Amelia', 'Sara', 'Samuel', 'Andres','Valentina','Jorge'],
        'Age': [28, 22, 25, 29, 31, 42, 33],
        'City': ['Cali', 'Bucaramanga', 'Cartajena', 'Cali', 'Popayan', 'Bucaramanga', 'Cartajena'],
        'Salary': [3700000, 1500000, 400000, 3200000, 2100000, 360000, 2900000]
    }
df = pd.DataFrame(data)
avg_salary = df.groupby('City')['Salary'].mean()
print("Salario promedio por ciudad:")
print(avg_salary)

Salario promedio por ciudad:
City
Bucaramanga     930000.0
Cali           3450000.0
Cartajena      1650000.0
Popayan        2100000.0
Name: Salary, dtype: float64


**15. Agrega una columna que indique si la persona es menor de 30 años (True o
False).**

In [ ]:
data = {
        'Name': ['Veronica', 'Amelia', 'Sara', 'Samuel', 'Andres','Valentina','Jorge'],
        'Age': [28, 22, 25, 29, 31, 42, 33],
    }
df = pd.DataFrame(data)
df['Under_30'] = df['Age'] < 30
print ("La persona es menor de 30 años? :")
print(df)

La persona es menor de 30 años? :
        Name  Age  Under_30
0   Veronica   28      True
1     Amelia   22      True
2       Sara   25      True
3     Samuel   29      True
4     Andres   31     False
5  Valentina   42     False
6      Jorge   33     False


**16. Reemplaza todos los valores nulos de una columna llamada Salario por el
promedio de esa columna.**

In [ ]:
data = {
    'Name': ['Veronica', 'Amelia', 'Sara', 'Samuel', 'Andres', 'Valentina', 'Jorge'],
    'Age': [28, 22, 25, 29, 31, 42, 33],
    'City': ['Cali', 'Bucaramanga', 'Cartagena', 'Medellin', 'Popayan', 'Cucuta', 'Pereira'],
    'Salary': [np.nan, 1500000, np.nan , 3200000, 2100000, 360000, np.nan]
}

df = pd.DataFrame(data)
print("Salarios con valores nulos:")
print(df)
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print("Salarios sin valores nulos reemplazados por el promedio de la columna")
print(df)


Salarios con valores nulos:
        Name  Age         City     Salary
0   Veronica   28         Cali        NaN
1     Amelia   22  Bucaramanga  1500000.0
2       Sara   25    Cartagena        NaN
3     Samuel   29     Medellin  3200000.0
4     Andres   31      Popayan  2100000.0
5  Valentina   42       Cucuta   360000.0
6      Jorge   33      Pereira        NaN
Salarios sin valores nulos reemplazados por el promedio de la columna
        Name  Age         City     Salary
0   Veronica   28         Cali  1790000.0
1     Amelia   22  Bucaramanga  1500000.0
2       Sara   25    Cartagena  1790000.0
3     Samuel   29     Medellin  3200000.0
4     Andres   31      Popayan  2100000.0
5  Valentina   42       Cucuta   360000.0
6      Jorge   33      Pereira  1790000.0


**17. Crea un DataFrame con columnas duplicadas y elimina las duplicadas dejando solo una copia.**

In [ ]:
df_dup = pd.DataFrame({
    'Name': ['Veronica', 'Amelia', 'Sara', 'Samuel', 'Andres', 'Valentina', 'Jorge'],
    'Name_dup': ['Veronica', 'Amelia', 'Sara', 'Samuel', 'Andres', 'Valentina', 'Jorge'],
    'Age': [28, 22, 25, 29, 31, 42, 33],
    'City': ['Cali', 'Bucaramanga', 'Cartagena', 'Medellin', 'Popayan', 'Cucuta', 'Pereira'],
    'City_dup': ['Cali', 'Bucaramanga', 'Cartagena', 'Medellin', 'Popayan', 'Cucuta', 'Pereira'],
    'Salary': [3700000, 1500000, 400000, 3200000, 2100000, 360000, 290000]
})
print("DataFrame con columnas duplicadas:")
print(df_dup)
df_no_dup = df_dup.T.drop_duplicates().T
print(" DataFrame con las columnas duplicadas eliminadas:")
print(df_no_dup)

DataFrame con columnas duplicadas:
        Name   Name_dup  ...     City_dup   Salary
0   Veronica   Veronica  ...         Cali  3700000
1     Amelia     Amelia  ...  Bucaramanga  1500000
2       Sara       Sara  ...    Cartagena   400000
3     Samuel     Samuel  ...     Medellin  3200000
4     Andres     Andres  ...      Popayan  2100000
5  Valentina  Valentina  ...       Cucuta   360000
6      Jorge      Jorge  ...      Pereira   290000

[7 rows x 6 columns]
 DataFrame con las columnas duplicadas eliminadas:
        Name Age         City   Salary
0   Veronica  28         Cali  3700000
1     Amelia  22  Bucaramanga  1500000
2       Sara  25    Cartagena   400000
3     Samuel  29     Medellin  3200000
4     Andres  31      Popayan  2100000
5  Valentina  42       Cucuta   360000
6      Jorge  33      Pereira   290000


**18. Ordena un DataFrame por dos columnas: primero por Ciudad alfabéticamente y luego por Edad de mayor a menor.**

In [ ]:
data = {
    'Name': ['Veronica', 'Amelia', 'Sara', 'Samuel', 'Andres', 'Valentina', 'Jorge'],
    'Age': [28, 22, 25, 29, 31, 42, 33],
    'City': ['Cali', 'Bucaramanga', 'Cartagena', 'Medellin', 'Popayan', 'Cucuta', 'Pereira'],
   }

df = pd.DataFrame(data)
df_city_sorted = df.sort_values(by='City', ascending=True)
print("Cuidad en orden alfabetico :")
print(df_city_sorted)

df_age_sorted = df.sort_values(by='Age', ascending=False)
print("Edad de mayor a menor:")
print(df_age_sorted)

Cuidad en orden alfabetico :
        Name  Age         City
1     Amelia   22  Bucaramanga
0   Veronica   28         Cali
2       Sara   25    Cartagena
5  Valentina   42       Cucuta
3     Samuel   29     Medellin
6      Jorge   33      Pereira
4     Andres   31      Popayan
Edad de mayor a menor:
        Name  Age         City
5  Valentina   42       Cucuta
6      Jorge   33      Pereira
4     Andres   31      Popayan
3     Samuel   29     Medellin
0   Veronica   28         Cali
2       Sara   25    Cartagena
1     Amelia   22  Bucaramanga


# **Preguntas complejas**

**19. Dado el siguiente DataFrame
df = pd.DataFrame({
'Producto': ['A', 'B', 'A', 'C', 'B', 'A'],
'Precio': [1200, 1500, 1300, 1000, 1600, 1250],
'Cantidad': [3, 2, 5, 1, 2, 4]
}). Agrupa por Producto, calcula el ingreso total (Precio * Cantidad) por producto y ordénalo de mayor a menor.**

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    'Producto': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Precio': [1200, 1500, 1300, 1000, 1600, 1250],
    'Cantidad': [3, 2, 5, 1, 2, 4]
    })

Outcome = ( df .assign(Ingreso=df['Precio'] * df['Cantidad'])
    .groupby('Producto')['Ingreso'].sum()
    .sort_values(ascending=False)
    .reset_index())
print(Outcome)


  Producto  Ingreso
0        A    15100
1        B     6200
2        C     1000


**20. Con un DataFrame de 1000 registros de ventas simuladas (puedes generarlo
con datos aleatorios que incluyan columnas como fecha, producto,
cantidad, precio_unitario, zona), responde: ¿Cuál es el producto más vendido por zona?, ¿Qué día del mes se obtienen más ingresos?.**

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

In [ ]:
np.random.seed(42)


products = [
    'Tubos de ensayo', 'Erlenmeyer', 'Probetas', 'Beakers',
    'Pipetas', 'Buretas', 'Matraces aforados', 'Vidrio reloj',
    'Embudos', 'Termometros', 'Desecadores', 'Picnometros']

base_price = {
    'Tubos de ensayo': 8500, 'Erlenmeyer': 23500, 'Probetas': 28700,'Beakers': 18500, 'Pipetas': 12400, 'Buretas': 68300,'Matraces aforados': 32500, 'Vidrio reloj': 7500, 'Embudos': 15200,
    'Termometros': 21300, 'Desecadores': 89500, 'Picnometros': 112000}

locations = ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga']

data = {    'date': pd.date_range('2023-01-01', '2023-12-31').to_series().sample(1000, replace=True).values,
    'Producto': np.random.choice(products, 1000),
    'Cantidad': np.random.randint(1, 16, 1000),
    'Ubicación': np.random.choice(locations, 1000)}

df = pd.DataFrame(data)

def assign_price(product):
    base = base_price[product]
    return base * (1 + np.random.uniform(-0.15, 0.15))

df['unit_price'] = df['Producto'].apply(assign_price).round(2)
df['income'] = (df['Cantidad'] * df['unit_price']).round(2)

sales_by_location = df.groupby(['Ubicación', 'Producto'])['Cantidad'].sum().reset_index()
top_product_per_location = sales_by_location.loc[sales_by_location.groupby('Ubicación')['Cantidad'].idxmax()]

df['día del mes'] = df['date'].dt.day
income_by_day = df.groupby('día del mes')['income'].sum().reset_index()
max_income_day = income_by_day.loc[income_by_day['income'].idxmax()]

print("="*50)
print("Producto más vendido por ciudad")
print("="*50)
print(top_product_per_location[['Ubicación', 'Producto', 'Cantidad']].to_string(index=False))

print("\n" + "="*50)
print(f"Día con más ingresos:Día N° {int(max_income_day['día del mes'])}")
print(f"Ingresos totales: ${max_income_day['income']:,.2f} COP")
print("="*50)

print("\n 5 días con mayores ingresos:")
top_5_days = income_by_day.sort_values('income', ascending=False).head(5).reset_index(drop=True)
top_5_days.columns = ['Día del mes', 'Ingresos totales (COP)']
print(top_5_days)

Producto más vendido por ciudad
   Ubicación     Producto  Cantidad
Barranquilla Vidrio reloj       174
      Bogotá   Erlenmeyer       179
 Bucaramanga      Embudos       196
        Cali     Probetas       157
   Cartagena      Buretas       173
    Medellín      Pipetas       166

Día con más ingresos:Día N° 9
Ingresos totales: $15,656,506.38 COP

 5 días con mayores ingresos:
   Día del mes  Ingresos totales (COP)
0            9             15656506.38
1           11             13508088.85
2            8             13356464.27
3           21             12164945.53
4           23             11968795.74
